# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53526022dfffb723b9837893fe4307b2a501a7479877cf1f12afd585e8cde6ad6bc8e82a9772611528915c6da19ff5964e05c287595d4dc1bb9a74f3b48cb718

test:
  secret_key_base: a109e4370d1adbf14ad7f8132f44b4f297c3ccdd0235c66d3dff0d757a982dee33b7cbd6a665de077fe35cc39381def83b266f144df59525eed476ba3ff2409f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
